_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]

MODEL:
  FREEZE_LAYERS:  [  ] #backbone
  META_ARCHITECTURE: BaselineOim
  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 50x
    WITH_IBN: False
    WITH_NL:  False
  # WEIGHTS: "./logs/Pet/sbs_resnest101_101/model_best.pth"
  # LOSSES:
  #   NAME: ("OimLoss",) #"CrossEntropyLoss", 
  #   CE:
  #     EPSILON: 0.1
  #     SCALE: 1.0
  #   OIM:
  #     SCALE: 1.0
  LOSSES:
    NAME: ("OIMLoss",) #"CrossEntropyLoss", 
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    OIM:
      SCALE: 1.0
  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    EMBEDDING_DIM: 0
    NECK_FEAT: after
    POOL_LAYER: GeneralizedMeanPoolingP
    CLS_LAYER: Linear
    # SCALE: 64
    # MARGIN: 0.35

SOLVER:
  AMP:
    ENABLED: False
  # OPT: Adam
  # SCHED: CosineAnnealingLR
  # BASE_LR: 0.0007
  # BIAS_LR_FACTOR: 1.
  # ETA_MIN_LR: 7.7e-5
  OPT: Adam
  MAX_EPOCH: 60
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64
  SCHED: MultiStepLR
  STEPS: [ 30, 50, 70 ]
  GAMMA: 0.1
  WARMUP_ITERS: 2000
  # FREEZE_ITERS: 1000
  CHECKPOINT_PERIOD: 20
  DELAY_EPOCHS: 0
DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

DATALOADER: 
  SAMPLER_TRAIN: BalancedIdentitySampler
  NUM_INSTANCE: 4
TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 256
OUTPUT_DIR: market1501oim  #debug_hard_contra2#