_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [384, 384]
  SIZE_TEST: [384, 384]

MODEL:
  FREEZE_LAYERS: []
  META_ARCHITECTURE: BaselineOim
  BACKBONE:
    NAME: build_resnest_backbone
    DEPTH: 101x
    WITH_IBN: True
    WITH_NL:  True
  # WEIGHTS: "./resnest101_all_data/model_best.pth"
  LOSSES:
    NAME: ("OimLoss", "Cosface",)  #"CrossEntropyLoss", 
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    OIM:
      SCALE: 1.0
    COSFACE:
      MARGIN: 0.35
      GAMMA: 64
      SCALE: 1.0
  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    EMBEDDING_DIM: 0
    NECK_FEAT: after
    POOL_LAYER: GeneralizedMeanPoolingP
    CLS_LAYER: Linear
    # SCALE: 64
    # MARGIN: 0.35

SOLVER:
  AMP:
    ENABLED: False
  # OPT: Adam
  # SCHED: CosineAnnealingLR
  # BASE_LR: 0.0007
  # BIAS_LR_FACTOR: 1.
  # ETA_MIN_LR: 7.7e-5
  OPT: Adam
  MAX_EPOCH: 60
  BASE_LR: 0.000035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 24 #
  SCHED: MultiStepLR
  STEPS: [ 30, 50, 70 ]
  GAMMA: 0.1
  WARMUP_ITERS: 3000
  # FREEZE_ITERS: 3000
  CHECKPOINT_PERIOD: 5
  DELAY_EPOCHS: 0
DATASETS:
  NAMES: ("Pet",)
  TESTS: ("Pet",)

DATALOADER: 
  SAMPLER_TRAIN: BalancedIdentitySampler
  NUM_INSTANCE: 2
TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 256
OUTPUT_DIR: resnest101_all_data_finetune