_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    WITH_NL: True
  WEIGHTS: "/home/lzy/fast-reid/logs/Pet/sbs_R50-ibn_all_data_2instance_cosface/model_best.pth"
  LOSSES:
    NAME: ("CrossEntropyLoss", "Cosface",)
    CE:
      EPSILON: 0.
      SCALE: 1.
    TRI:
      MARGIN: 0.
      HARD_MINING: True
      NORM_FEAT: True
      SCALE: 1.
    COSFACE:
      MARGIN: 0.35
      GAMMA: 64
      SCALE: 1.
SOLVER:
  OPT: Adam
  BASE_LR: 0.00035 #0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 64
  MAX_EPOCH: 100
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000
  CHECKPOINT_PERIOD: 10
DATASETS:
  NAMES: ("Pet",)
  TESTS: ("Pet",)

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler
  NUM_INSTANCE: 2
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256
OUTPUT_DIR: logs/Pet/sbs_R50-ibn_all_data_2instance_cosface_resume