_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
MODEL:
  BACKBONE:
    WITH_IBN: True
    WITH_NL: True
  # WEIGHTS: "/home/lzy/fast-reid/logs/Pet/sbs_R50-ibn_all_data_2instance/model_best.pth"
SOLVER:
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 64
  MAX_EPOCH: 80
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000
  CHECKPOINT_PERIOD: 10
DATASETS:
  NAMES: ("Pet",)
  TESTS: ("Pet",)

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler
  NUM_INSTANCE: 4
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256
OUTPUT_DIR: logs/Pet/sbs_R50-ibn_all_data_4instance