_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]

MODEL:
  FREEZE_LAYERS: []
  META_ARCHITECTURE: BaselineOim
  BACKBONE:
    FEAT_DIM: 1024
    NAME: build_SwinTransformer_backbone
    # DEPTH: 101x
    # WITH_IBN: True
    # WITH_NL:  True
  # WEIGHTS: "./logs/Pet/sbs_resnest101_101/model_best.pth"
  LOSSES:
    NAME: ("OimLoss",) #"CrossEntropyLoss", 
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    OIM:
      SCALE: 1.0
  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    EMBEDDING_DIM: 0
    NECK_FEAT: after
    POOL_LAYER: Identity_trans
    CLS_LAYER: Linear
    # SCALE: 64
    # MARGIN: 0.35


  # TYPE: swin_mlp
  # NAME: swin_mlp_base_patch4_window7_224
  # DROP_PATH_RATE: 0.5
  # SWIN_MLP:
  #   EMBED_DIM: 128
  #   DEPTHS: [ 2, 2, 18, 2 ]
  #   NUM_HEADS: [ 4, 8, 16, 32 ]
  #   WINDOW_SIZE: 7
    
  TYPE: swin
  NAME: swin_base_patch4_window7_224_22k
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7

SOLVER:
  AMP:
    ENABLED: False
  # OPT: Adam
  # SCHED: CosineAnnealingLR
  # BASE_LR: 0.0007
  # BIAS_LR_FACTOR: 1.
  # ETA_MIN_LR: 7.7e-5
  OPT: Adam
  MAX_EPOCH: 90
  BASE_LR: 0.00001
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64 #
  SCHED: MultiStepLR
  STEPS: [ 30, 50, 70 ]
  GAMMA: 0.1
  WARMUP_ITERS: 3000
  # FREEZE_ITERS: 3000
  CHECKPOINT_PERIOD: 10
  DELAY_EPOCHS: 0
DATASETS:
  NAMES: ("Pet",)
  TESTS: ("Pet",)

DATALOADER: 
  SAMPLER_TRAIN: BalancedIdentitySampler
  NUM_INSTANCE: 4
TEST:
  EVAL_PERIOD: 4
  IMS_PER_BATCH: 256
OUTPUT_DIR: logs/Pet/sbs_resnest101_101_swin
